In [1]:
#!/usr/bin/env python3
#generating N*N magic square where N is 
# an odd number based on Lo Shu's 3 x 3 square

import numpy as np
import math

N = int(input("please enter an odd number:"))
odd_square = np.zeros((N,N), dtype = int)

n = 1
i,j = 0, N//2

while n <= N**2:
    odd_square[i,j] = n
    n += 1
    newi,newj = (i-1)%N,(j+1)%N
    if odd_square[newi,newj]:
        i += 1
    else:
       i,j = newi,newj
print('\ngenerate magic square of order %i' %(N))     
print(odd_square)
print('\nconstant for the magic square %i' % ((N * N + 1) * N//2))   

def magic_square(my_matrix):
     inputsize = len(my_matrix)
     sum_list = []
     #rows
     sum_list.extend(sum(lines)for lines in my_matrix)
     #columns
     for col in range(inputsize):
         sum_list.append(sum(row[col] for row in my_matrix))
     #diagonals:
     result1 = 0
     for i in range(0,inputsize):
         result1 += my_matrix[i][i]
         sum_list.append(result1)
     result2 = 0
     for i in range(inputsize-1,-1,-1):
         result2 += my_matrix[i][i]
         sum_list.append(result2)
     if len(set(sum_list))>1:
         return " valid magic square"
     else:
         return " not valid magic square"
 
print(magic_square(odd_square))
          

please enter an odd number:3

generate magic square of order 3
[[8 1 6]
 [3 5 7]
 [4 9 2]]

constant for the magic square 15
 valid magic square
